[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read-write", path = "./.env"},
    { access = "read", path = "./mc.toml" },
    { access = "read", path = "./lib/mc/mc.toml" },
    { access = "read-write", path = "./"}
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
